export const promotionalTestData = {
  id: 'promo-general-knowledge',
  title: {
    mr: 'सामान्य ज्ञान चाचणी - मोफत',
    en: 'General Knowledge Test - Free'
  },
  description: {
    mr: 'अर्थशास्त्र, संगणक, खगोल, भूविज्ञान, संविधान, इतिहास, भौतिक आणि जीवशास्त्र',
    en: 'Economics, Computer, Astronomy, Earth Science, Constitution, History, Physics & Biology'
  },
  duration: 60,
  totalQuestions: 50,
  isFree: true,
  isPromotional: true,
  questions: [
    { id: 1, question: { mr: "अर्थशास्त्रातील 'द वेल्थ ऑफ नेशन्स' या पुस्तकाचे लेखक कोण आहेत?", en: "Who is the author of 'The Wealth of Nations' in economics?" }, options: { mr: ["कार्ल मार्क्स", "जॉन मेनार्ड केन्स", "अॅडम स्मिथ", "मिल्टन फ्रीडमन"], en: ["Karl Marx", "John Maynard Keynes", "Adam Smith", "Milton Friedman"] }, correct: 2, explanation: { mr: "Adam Smith यांनी 'The Wealth of Nations' (1776) लिहिले, जे आधुनिक अर्थशास्त्राचा पाया मानला जातो.", en: "Adam Smith wrote 'The Wealth of Nations' (1776), considered the foundation of modern economics with concepts like the invisible hand and free markets." } },
    { id: 2, question: { mr: "बेरोजगारीचा दर मोजण्यासाठी कोणता सूत्र वापरला जातो?", en: "Which formula is used to calculate unemployment rate?" }, options: { mr: ["(बेरोजगार व्यक्ती / एकूण लोकसंख्या) × 100", "(बेरोजगार व्यक्ती / श्रमशक्ती) × 100", "(रोजगारप्राप्त व्यक्ती / श्रमशक्ती) × 100", "(बेरोजगार व्यक्ती / एकूण रोजगारप्राप्त व्यक्ती) × 100"], en: ["(Unemployed persons / Total population) × 100", "(Unemployed persons / Labor force) × 100", "(Employed persons / Labor force) × 100", "(Unemployed persons / Total employed persons) × 100"] }, correct: 1, explanation: { mr: "बेरोजगारीचा दर = (बेरोजगार / श्रमशक्ती) × 100. श्रमशक्ती = रोजगारप्राप्त + काम शोधणारे बेरोजगार.", en: "Unemployment rate formula uses labor force (employed + unemployed seeking work) as denominator, not total population." } },
    { id: 3, question: { mr: "'द जनरल थिअरी ऑफ एम्प्लॉयमेंट, इंटरेस्ट अँड मनी' या पुस्तकात कोणत्या अर्थशास्त्रज्ञाने बेरोजगारीवर उपाय सुचवले?", en: "Which economist suggested solutions for unemployment in 'The General Theory of Employment, Interest and Money'?" }, options: { mr: ["अॅडम स्मिथ", "जॉन मेनार्ड केन्स", "डेव्हिड रिकार्डो", "थॉमस माल्थस"], en: ["Adam Smith", "John Maynard Keynes", "David Ricardo", "Thomas Malthus"] }, correct: 1, explanation: { mr: "Keynes यांनी 'The General Theory' (1936) मध्ये बेरोजगारी कमी करण्यासाठी सरकारी हस्तक्षेप आणि मागणी वाढवण्याचे सुचवले.", en: "Keynes wrote 'The General Theory' (1936) advocating government intervention and demand stimulation to reduce unemployment." } },
    { id: 4, question: { mr: "खालीलपैकी कोणता बेरोजगारीचा प्रकार हंगामी स्वरूपाचा आहे?", en: "Which of the following is a seasonal type of unemployment?" }, options: { mr: ["संरचनात्मक बेरोजगारी", "चक्रीय बेरोजगारी", "हंगामी बेरोजगारी", "घर्षणात्मक बेरोजगारी"], en: ["Structural unemployment", "Cyclical unemployment", "Seasonal unemployment", "Frictional unemployment"] }, correct: 2, explanation: { mr: "हंगामी बेरोजगारी विशिष्ट हंगामात होते जेव्हा शेती किंवा पर्यटन सारख्या उद्योगांची क्रिया कमी होते.", en: "Seasonal unemployment occurs during specific seasons when industries like agriculture or tourism have reduced activity." } },
    { id: 5, question: { mr: "'कॅपिटल: ए क्रिटीक ऑफ पॉलिटिकल इकॉनॉमी' या पुस्तकात कोणत्या अर्थशास्त्रज्ञाने मजूर आणि भांडवल यांच्यातील संबंधांवर चर्चा केली?", en: "Which economist discussed the relationship between labor and capital in 'Capital: A Critique of Political Economy'?" }, options: { mr: ["जॉन मेनार्ड केन्स", "कार्ल मार्क्स", "अॅडम स्मिथ", "मिल्टन फ्रीडमन"], en: ["John Maynard Keynes", "Karl Marx", "Adam Smith", "Milton Friedman"] }, correct: 1, explanation: { mr: "Karl Marx यांनी 'Das Kapital' (1867) मध्ये भांडवलशाही व्यवस्थेत मजूर आणि भांडवल यांच्यातील शोषणकारी संबंधांचे विश्लेषण केले.", en: "Karl Marx analyzed the exploitative relationship between labor and capital in capitalist systems in 'Das Kapital' (1867)." } },
    { id: 6, question: { mr: "Windows ऑपरेटिंग सिस्टीममध्ये सर्वकाही निवडण्यासाठी (Select All) कोणता शॉर्टकट की वापरला जातो?", en: "Which shortcut key is used for Select All in Windows operating system?" }, options: { mr: ["Ctrl + C", "Ctrl + A", "Ctrl + S", "Ctrl + Z"], en: ["Ctrl + C", "Ctrl + A", "Ctrl + S", "Ctrl + Z"] }, correct: 1, explanation: { mr: "Ctrl + A हा Windows अनुप्रयोगांमध्ये 'Select All' साठी सार्वत्रिक शॉर्टकट आहे.", en: "Ctrl + A is the universal shortcut for 'Select All' in Windows applications." } },
    { id: 7, question: { mr: "Microsoft Word मध्ये एखादा शब्द किंवा मजकूर ठळक (Bold) करण्यासाठी कोणता शॉर्टकट की वापरला जातो?", en: "Which shortcut key is used to make text bold in Microsoft Word?" }, options: { mr: ["Ctrl + B", "Ctrl + I", "Ctrl + U", "Ctrl + T"], en: ["Ctrl + B", "Ctrl + I", "Ctrl + U", "Ctrl + T"] }, correct: 0, explanation: { mr: "Ctrl + B हा Microsoft Word आणि इतर टेक्स्ट एडिटरमध्ये मजकूर ठळक करण्यासाठी मानक शॉर्टकट आहे.", en: "Ctrl + B is the standard shortcut for making text bold in Microsoft Word and other text editors." } },
    { id: 8, question: { mr: "वेब ब्राउझरमध्ये नवीन टॅब उघडण्यासाठी कोणता शॉर्टकट की वापरला जातो?", en: "Which shortcut key is used to open a new tab in web browser?" }, options: { mr: ["Ctrl + N", "Ctrl + T", "Ctrl + W", "Ctrl + R"], en: ["Ctrl + N", "Ctrl + T", "Ctrl + W", "Ctrl + R"] }, correct: 1, explanation: { mr: "Ctrl + T हा Chrome, Firefox आणि Edge सारख्या वेब ब्राउझरमध्ये नवीन टॅब उघडण्यासाठी वापरला जातो.", en: "Ctrl + T opens a new tab in web browsers like Chrome, Firefox, and Edge." } },
    { id: 9, question: { mr: "Windows मध्ये स्क्रीनचा स्क्रीनशॉट घेण्यासाठी कोणता शॉर्टकट की वापरला जातो?", en: "Which shortcut key is used to take a screenshot in Windows?" }, options: { mr: ["Alt + Print Screen", "Ctrl + Print Screen", "Print Screen", "Windows Key + S"], en: ["Alt + Print Screen", "Ctrl + Print Screen", "Print Screen", "Windows Key + S"] }, correct: 2, explanation: { mr: "Print Screen की संपूर्ण स्क्रीन कॅप्चर करून Windows मध्ये clipboard मध्ये सेव्ह करते.", en: "Print Screen key captures the entire screen and saves it to clipboard in Windows." } },
    { id: 10, question: { mr: "Microsoft Excel मध्ये निवडलेल्या सेल्समधील डेटा कॉपी करण्यासाठी कोणता शॉर्टकट की वापरला जातो?", en: "Which shortcut key is used to copy data from selected cells in Microsoft Excel?" }, options: { mr: ["Ctrl + X", "Ctrl + C", "Ctrl + V", "Ctrl + P"], en: ["Ctrl + X", "Ctrl + C", "Ctrl + V", "Ctrl + P"] }, correct: 1, explanation: { mr: "Ctrl + C हा Excel आणि इतर Microsoft Office अनुप्रयोगांमध्ये सार्वत्रिक कॉपी कमांड आहे.", en: "Ctrl + C is the universal copy command in Excel and other Microsoft Office applications." } },
    { id: 11, question: { mr: "सूर्यमालेतील सर्वात मोठा ग्रह कोणता आहे?", en: "Which is the largest planet in the solar system?" }, options: { mr: ["मंगळ", "गुरु (Jupiter)", "शनि", "पृथ्वी"], en: ["Mars", "Jupiter", "Saturn", "Earth"] }, correct: 1, explanation: { mr: "गुरु हा आपल्या सूर्यमालेतील सर्वात मोठा ग्रह आहे, ज्याचा व्यास अंदाजे 139,820 किमी आहे.", en: "Jupiter is the largest planet in our solar system with a diameter of approximately 139,820 km." } },
    { id: 12, question: { mr: "खालीलपैकी कोणता ग्रह सूर्यापासून तिसऱ्या क्रमांकावर आहे?", en: "Which planet is third from the Sun?" }, options: { mr: ["शुक्र", "पृथ्वी", "मंगळ", "बुध"], en: ["Venus", "Earth", "Mars", "Mercury"] }, correct: 1, explanation: { mr: "सूर्यापासून क्रम: बुध, शुक्र, पृथ्वी, मंगळ - त्यामुळे पृथ्वी तिसऱ्या स्थानावर आहे.", en: "The order from the Sun is: Mercury, Venus, Earth, Mars - making Earth the third planet." } },
    { id: 13, question: { mr: "शनीच्या कड्यांचे (Rings) मुख्य घटक काय आहे?", en: "What are the main components of Saturn's rings?" }, options: { mr: ["लोह आणि खडक", "बर्फ आणि धूळ", "हायड्रोजन आणि हेलियम", "अमोनिया आणि मिथेन"], en: ["Iron and rock", "Ice and dust", "Hydrogen and helium", "Ammonia and methane"] }, correct: 1, explanation: { mr: "शनीच्या कड्या प्रामुख्याने बर्फाचे कण आणि धूळ यांनी बनलेल्या आहेत, खडक किंवा वायूंनी नाही.", en: "Saturn's rings are primarily composed of ice particles and dust, not rock or gases." } },
    { id: 14, question: { mr: "सूर्यमालेतील सर्वात लहान ग्रह कोणता आहे?", en: "Which is the smallest planet in the solar system?" }, options: { mr: ["बुध", "मंगळ", "शुक्र", "युरेनस"], en: ["Mercury", "Mars", "Venus", "Uranus"] }, correct: 0, explanation: { mr: "बुध हा आपल्या सूर्यमालेतील सर्वात लहान ग्रह आहे, ज्याचा व्यास अंदाजे 4,880 किमी आहे.", en: "Mercury is the smallest planet in our solar system with a diameter of approximately 4,880 km." } },
    { id: 15, question: { mr: "खालीलपैकी कोणता ग्रह 'गॅस जायंट' (Gas Giant) म्हणून ओळखला जातो?", en: "Which of the following planets is known as a 'Gas Giant'?" }, options: { mr: ["पृथ्वी", "मंगळ", "गुरु (Jupiter)", "बुध"], en: ["Earth", "Mars", "Jupiter", "Mercury"] }, correct: 2, explanation: { mr: "गुरु हा गॅस जायंट आहे जो प्रामुख्याने हायड्रोजन आणि हेलियमने बनलेला आहे, स्थलीय ग्रहांप्रमाणे नाही.", en: "Jupiter is a gas giant composed primarily of hydrogen and helium, unlike terrestrial planets." } },
    { id: 16, question: { mr: "पृथ्वीच्या अंतरंगाचा सर्वात आतील थर कोणता आहे?", en: "Which is the innermost layer of Earth's interior?" }, options: { mr: ["भूपृष्ठ (Crust)", "प्रावरण (Mantle)", "बाह्य गाभा (Outer Core)", "आंतरिक गाभा (Inner Core)"], en: ["Crust", "Mantle", "Outer Core", "Inner Core"] }, correct: 3, explanation: { mr: "पृथ्वीचे थर बाहेरून आतपर्यंत: भूपृष्ठ, प्रावरण, बाह्य गाभा आणि आंतरिक गाभा (सर्वात खोल थर).", en: "Earth's layers from outside to inside are: crust, mantle, outer core, and inner core (deepest layer)." } },
    { id: 17, question: { mr: "पृथ्वीच्या प्रावरण (Mantle) मध्ये प्रामुख्याने कोणता पदार्थ आढळतो?", en: "Which substance is primarily found in Earth's mantle?" }, options: { mr: ["लोह आणि निकेल", "सिलिकेट खडक", "बर्फ आणि पाणी", "हायड्रोजन आणि हेलियम"], en: ["Iron and nickel", "Silicate rock", "Ice and water", "Hydrogen and helium"] }, correct: 1, explanation: { mr: "पृथ्वीचे प्रावरण प्रामुख्याने मॅग्नेशियम आणि लोह संयुगे असलेल्या सिलिकेट खडकांनी बनलेले आहे.", en: "Earth's mantle is primarily composed of silicate rocks containing magnesium and iron compounds." } },
    { id: 18, question: { mr: "पृथ्वीच्या चुंबकीय क्षेत्राचे मुख्य कारण कोणते आहे?", en: "What is the main cause of Earth's magnetic field?" }, options: { mr: ["भूपृष्ठ (Crust)", "बाह्य गाभा (Outer Core)", "प्रावरण (Mantle)", "लिथोस्फीअर (Lithosphere)"], en: ["Crust", "Outer Core", "Mantle", "Lithosphere"] }, correct: 1, explanation: { mr: "पृथ्वीचे चुंबकीय क्षेत्र बाह्य गाभ्यातील द्रव लोह आणि निकेलच्या हालचालीमुळे निर्माण होते (डायनामो इफेक्ट).", en: "Earth's magnetic field is generated by the movement of liquid iron and nickel in the outer core (dynamo effect)." } },
    { id: 19, question: { mr: "पृथ्वीच्या भूपृष्ठाचा (Crust) सर्वात पातळ भाग कोणत्या ठिकाणी आढळतो?", en: "Where is the thinnest part of Earth's crust found?" }, options: { mr: ["हिमालय पर्वतरांगा", "महासागर खालचा भाग", "मैदानी प्रदेश", "ज्वालामुखी परिसर"], en: ["Himalayan mountain range", "Ocean floor", "Plains", "Volcanic regions"] }, correct: 1, explanation: { mr: "समुद्री भूपृष्ठ (5-10 किमी) खंडीय भूपृष्ठाच्या (30-50 किमी) तुलनेत पातळ आहे.", en: "Oceanic crust is thinner (5-10 km) compared to continental crust (30-50 km)." } },
    { id: 20, question: { mr: "पृथ्वीच्या आंतरिक गाभ्याची (Inner Core) अवस्था काय आहे?", en: "What is the state of Earth's inner core?" }, options: { mr: ["द्रव", "घन", "वायू", "अर्ध-द्रव"], en: ["Liquid", "Solid", "Gas", "Semi-liquid"] }, correct: 1, explanation: { mr: "अत्यंत उच्च तापमान असूनही, वरच्या थरांच्या प्रचंड दाबामुळे आंतरिक गाभा घन आहे.", en: "Despite extremely high temperatures, the inner core is solid due to immense pressure from overlying layers." } },
    { id: 21, question: { mr: "भारताच्या घटना समितीची स्थापना कोणत्या वर्षी झाली?", en: "In which year was India's Constituent Assembly established?" }, options: { mr: ["१९४५", "१९४६", "१९४७", "१९४८"], en: ["1945", "1946", "1947", "1948"] }, correct: 1, explanation: { mr: "घटना समितीची स्थापना 1946 मध्ये कॅबिनेट मिशन योजनेच्या शिफारशींवर आधारित झाली.", en: "The Constituent Assembly was established in 1946 based on Cabinet Mission Plan recommendations." } },
    { id: 22, question: { mr: "घटना समितीच्या स्थायी अध्यक्षपदी कोणाची निवड झाली?", en: "Who was elected as the permanent president of the Constituent Assembly?" }, options: { mr: ["जवाहरलाल नेहरू", "डॉ. राजेंद्र प्रसाद", "डॉ. बाबासाहेब आंबेडकर", "सरदार वल्लभभाई पटेल"], en: ["Jawaharlal Nehru", "Dr. Rajendra Prasad", "Dr. Babasaheb Ambedkar", "Sardar Vallabhbhai Patel"] }, correct: 1, explanation: { mr: "डॉ. राजेंद्र प्रसाद यांची 11 डिसेंबर 1946 रोजी घटना समितीचे स्थायी अध्यक्ष म्हणून निवड झाली.", en: "Dr. Rajendra Prasad was elected permanent President of the Constituent Assembly on December 11, 1946." } },
    { id: 23, question: { mr: "घटना समितीच्या प्रसूदा समितीचे अध्यक्ष कोण होते?", en: "Who was the chairman of the Drafting Committee of the Constituent Assembly?" }, options: { mr: ["बी.एन. राव", "डॉ. बाबासाहेब आंबेडकर", "के.एम. मुन्शी", "अल्लादी कृष्णस्वामी अय्यर"], en: ["B.N. Rao", "Dr. Babasaheb Ambedkar", "K.M. Munshi", "Alladi Krishnaswami Ayyar"] }, correct: 1, explanation: { mr: "डॉ. बी.आर. आंबेडकर यांची 30 ऑगस्ट 1947 रोजी प्रसूदा समितीचे अध्यक्ष म्हणून एकमताने निवड झाली.", en: "Dr. B.R. Ambedkar was unanimously elected Chairman of the Drafting Committee on August 30, 1947." } },
    { id: 24, question: { mr: "भारतीय संविधानाचा प्रसूदा स्वीकारला गेला तो कोणता दिवस आहे?", en: "On which date was the draft of the Indian Constitution adopted?" }, options: { mr: ["२६ नोव्हेंबर १९४९", "१५ ऑगस्ट १९४७", "२६ जानेवारी १९५०", "९ डिसेंबर १९४६"], en: ["26 November 1949", "15 August 1947", "26 January 1950", "9 December 1946"] }, correct: 0, explanation: { mr: "संविधानाचा प्रसूदा 26 नोव्हेंबर 1949 रोजी स्वीकारला गेला, हा दिवस संविधान दिन म्हणून साजरा केला जातो.", en: "The Constitution draft was adopted on November 26, 1949, celebrated as Constitution Day, though it came into effect on January 26, 1950." } },
    { id: 25, question: { mr: "घटना समितीच्या पहिल्या बैठकीचे हंगामी अध्यक्ष कोण होते?", en: "Who was the temporary president of the first meeting of the Constituent Assembly?" }, options: { mr: ["सच्चिदानंद सिन्हा", "डॉ. राजेंद्र प्रसाद", "हरेंद्रकुमार मुखर्जी", "जी.व्ही. मावळणकर"], en: ["Sachchidanand Sinha", "Dr. Rajendra Prasad", "Harendra Kumar Mukherjee", "G.V. Mavalankar"] }, correct: 0, explanation: { mr: "सच्चिदानंद सिन्हा यांनी 9 डिसेंबर 1946 च्या पहिल्या बैठकीत हंगामी अध्यक्ष म्हणून काम केले.", en: "Sachidanand Sinha served as temporary President during the first meeting on December 9, 1946." } },
    { id: 26, question: { mr: "घटना समितीच्या स्थापनेसाठी कोणत्या योजनेच्या शिफारशी महत्त्वाच्या होत्या?", en: "Which plan's recommendations were important for establishing the Constituent Assembly?" }, options: { mr: ["क्रिप्स योजना", "कॅबिनेट मिशन योजना", "माउंटबॅटन योजना", "ऑगस्ट ऑफर"], en: ["Cripps Plan", "Cabinet Mission Plan", "Mountbatten Plan", "August Offer"] }, correct: 1, explanation: { mr: "कॅबिनेट मिशन योजना (1946) ने 389 सदस्यांसह घटना समिती स्थापन करण्याची चौकट प्रदान केली.", en: "The Cabinet Mission Plan (1946) provided the framework for establishing the Constituent Assembly with 389 members." } },
    { id: 27, question: { mr: "घटना समितीच्या एकूण किती अधिवेशनांचे आयोजन झाले?", en: "How many sessions of the Constituent Assembly were held in total?" }, options: { mr: ["१०", "११", "१२", "१३"], en: ["10", "11", "12", "13"] }, correct: 2, explanation: { mr: "घटना समितीने 9 डिसेंबर 1946 ते 24 जानेवारी 1950 पर्यंत 12 अधिवेशने आयोजित केली.", en: "The Constituent Assembly held 12 sessions from December 9, 1946, to January 24, 1950." } },
    { id: 28, question: { mr: "घटना समितीच्या प्रसूदा समितीची स्थापना कोणत्या तारखेला झाली?", en: "On which date was the Drafting Committee of the Constituent Assembly established?" }, options: { mr: ["९ डिसेंबर १९४६", "२९ ऑगस्ट १९४७", "२६ नोव्हेंबर १९४९", "२६ जानेवारी १९५०"], en: ["9 December 1946", "29 August 1947", "26 November 1949", "26 January 1950"] }, correct: 1, explanation: { mr: "प्रसूदा समितीची स्थापना 29 ऑगस्ट 1947 रोजी डॉ. आंबेडकर यांच्या अध्यक्षतेखाली झाली.", en: "The Drafting Committee was established on August 29, 1947, with Dr. Ambedkar as its Chairman." } },
    { id: 29, question: { mr: "घटना समितीच्या उद्दिष्टांबाबतचा ठराव कोणी मांडला?", en: "Who presented the resolution about the objectives of the Constituent Assembly?" }, options: { mr: ["डॉ. बाबासाहेब आंबेडकर", "जवाहरलाल नेहरू", "सरदार वल्लभभाई पटेल", "मौलाना अबुल कलाम आझाद"], en: ["Dr. Babasaheb Ambedkar", "Jawaharlal Nehru", "Sardar Vallabhbhai Patel", "Maulana Abul Kalam Azad"] }, correct: 1, explanation: { mr: "नेहरू यांनी 13 डिसेंबर 1946 रोजी उद्देश्य ठराव मांडला, जो संविधानाच्या प्रस्तावनेचा आधार बनला.", en: "Nehru presented the Objective Resolution on December 13, 1946, which became the basis for the Constitution's Preamble." } },
    { id: 30, question: { mr: "घटना समितीच्या एकूण सभासदांची संख्या सुरुवातीला किती होती?", en: "What was the initial total number of members in the Constituent Assembly?" }, options: { mr: ["२९९", "३८९", "२९२", "२११"], en: ["299", "389", "292", "211"] }, correct: 1, explanation: { mr: "सुरुवातीला घटना समितीत 389 सदस्य होते (ब्रिटिश प्रांतातून 292, मुख्य आयुक्त प्रांतातून 4, राजेशाही राज्यांतून 93).", en: "Initially, the Constituent Assembly had 389 members (292 from British provinces, 4 from Chief Commissioner provinces, 93 from princely states)." } },
    { id: 31, question: { mr: "वैदिक संस्कृतीचा सर्वात प्राचीन ग्रंथ कोणता आहे?", en: "Which is the oldest text of Vedic culture?" }, options: { mr: ["सामवेद", "ऋग्वेद", "यजुर्वेद", "अथर्ववेद"], en: ["Samaveda", "Rigveda", "Yajurveda", "Atharvaveda"] }, correct: 1, explanation: { mr: "ऋग्वेद हा सर्वात जुना वैदिक ग्रंथ आहे, जो सुमारे 1500-1200 ईसापूर्व रचला गेला.", en: "Rigveda is the oldest Vedic text, composed around 1500-1200 BCE, containing hymns to various deities." } },
    { id: 32, question: { mr: "वैदिक काळात समाजाची प्राथमिक सामाजिक रचना कोणती होती?", en: "What was the primary social structure of society in the Vedic period?" }, options: { mr: ["वर्ण व्यवस्था", "जाति व्यवस्था", "गणराज्य व्यवस्था", "कुटुंब व्यवस्था"], en: ["Varna system", "Caste system", "Republic system", "Family system"] }, correct: 0, explanation: { mr: "वैदिक समाज चार वर्णांमध्ये विभागला होता: ब्राह्मण, क्षत्रिय, वैश्य आणि शूद्र, जाति व्यवस्था नंतर विकसित झाली.", en: "Vedic society was organized into four varnas: Brahmana, Kshatriya, Vaishya, and Shudra, while caste system developed later." } },
    { id: 33, question: { mr: "वैदिक काळातील 'सप्तसिंधू' म्हणजे कोणता प्रदेश?", en: "What region does 'Saptasindhu' refer to in the Vedic period?" }, options: { mr: ["गंगा-यमुना खोरे", "पंजाब आणि सिंधू नदीचा प्रदेश", "दक्षिण भारत", "मध्य भारत"], en: ["Ganga-Yamuna valley", "Punjab and Indus river region", "South India", "Central India"] }, correct: 1, explanation: { mr: "सप्तसिंधू म्हणजे वैदिक काळातील पंजाब आणि सिंधू खोऱ्यातील सात नद्यांचा प्रदेश.", en: "Saptasindhu refers to the land of seven rivers in the Punjab and Indus valley region during Vedic times." } },
    { id: 34, question: { mr: "वैदिक संस्कृतीत कोणत्या देवतेची पूजा सर्वात प्रमुख होती?", en: "Which deity was most prominently worshipped in Vedic culture?" }, options: { mr: ["विष्णू", "इंद्र", "शिव", "ब्रह्मा"], en: ["Vishnu", "Indra", "Shiva", "Brahma"] }, correct: 1, explanation: { mr: "इंद्र, युद्ध आणि पावसाचा देव, वैदिक संस्कृतीत सर्वात प्रमुख देवता होता आणि ऋग्वेदात त्याला सर्वाधिक स्तुती आहेत.", en: "Indra, the god of war and rain, was the most prominent deity in Vedic culture with maximum hymns dedicated to him in Rigveda." } },
    { id: 35, question: { mr: "वैदिक ग्रंथांमध्ये यज्ञाचे वर्णन कोणत्या वेदात प्रामुख्याने आढळते?", en: "In which Veda is the description of yajna (sacrifice) primarily found in Vedic texts?" }, options: { mr: ["ऋग्वेद", "यजुर्वेद", "सामवेद", "अथर्ववेद"], en: ["Rigveda", "Yajurveda", "Samaveda", "Atharvaveda"] }, correct: 1, explanation: { mr: "यजुर्वेदात यज्ञांचे तपशीलवार वर्णन, मंत्र आणि कार्यपद्धती प्रामुख्याने आढळतात.", en: "Yajurveda primarily contains detailed descriptions of sacrificial rituals, mantras, and procedures for yajnas." } },
    { id: 36, question: { mr: "हडप्पा संस्कृतीचा कालखंड अंदाजे कोणता आहे?", en: "What is the approximate time period of the Harappan civilization?" }, options: { mr: ["इ.स.पू. ३५००-१५००", "इ.स.पू. २५००-१७००", "इ.स.पू. १५००-५००", "इ.स.पू. ५००-१००"], en: ["3500-1500 BCE", "2500-1700 BCE", "1500-500 BCE", "500-100 BCE"] }, correct: 1, explanation: { mr: "हडप्पा (सिंधू खोरे) संस्कृती अंदाजे 2500-1700 ईसापूर्व फलली-फुलली.", en: "The Harappan (Indus Valley) civilization flourished from approximately 2500-1700 BCE." } },
    { id: 37, question: { mr: "हडप्पा संस्कृतीच्या कोणत्या स्थळावर 'महान स्नानागार' (Great Bath) सापडले आहे?", en: "At which Harappan site was the 'Great Bath' discovered?" }, options: { mr: ["हडप्पा", "मोहेंजो-दारो", "लोथल", "धोलावीरा"], en: ["Harappa", "Mohenjo-daro", "Lothal", "Dholavira"] }, correct: 1, explanation: { mr: "महान स्नानागार, जे कदाचित धार्मिक आणि सामाजिक कारणांसाठी वापरले जात होते, मोहेंजो-दारो येथे सापडले.", en: "The Great Bath, likely used for religious and social purposes, was discovered at Mohenjo-daro." } },
    { id: 38, question: { mr: "हडप्पा संस्कृतीत कोणत्या धातूचा वापर सर्वप्रथम झाल्याचे पुरावे मिळाले?", en: "Evidence of which metal's use was first found in the Harappan civilization?" }, options: { mr: ["लोह", "तांबे", "सोने", "चांदी"], en: ["Iron", "Copper", "Gold", "Silver"] }, correct: 1, explanation: { mr: "हडप्पा संस्कृतीत तांबे हा पहिला धातू होता जो साधने आणि शस्त्रांसाठी वापरला गेला, लोह (सुमारे 1000 ईसापूर्व) पूर्वी.", en: "Copper was the first metal used in Harappan civilization for tools and weapons, before iron (around 1000 BCE)." } },
    { id: 39, question: { mr: "हडप्पा संस्कृतीच्या कोणत्या स्थळावर बंदर (Dockyard) सापडले आहे?", en: "At which Harappan site was a dockyard discovered?" }, options: { mr: ["कालीबंगन", "लोथल", "राखीगढी", "मोहेंजो-दारो"], en: ["Kalibangan", "Lothal", "Rakhigarhi", "Mohenjo-daro"] }, correct: 1, explanation: { mr: "लोथल येथे प्रगत बंदर व्यवस्था होती, जी हडप्पा संस्कृतीच्या समुद्री व्यापार संबंधांना दर्शवते.", en: "Lothal had an advanced dockyard system, indicating maritime trade connections of the Harappan civilization." } },
    { id: 40, question: { mr: "हडप्पा संस्कृतीच्या लिपीचे स्वरूप काय आहे?", en: "What is the nature of the Harappan script?" }, options: { mr: ["चित्रलिपी", "ब्राह्मी लिपी", "देवनागरी लिपी", "खरोष्ठी लिपी"], en: ["Pictographic", "Brahmi script", "Devanagari script", "Kharosthi script"] }, correct: 0, explanation: { mr: "हडप्पा लिपी चित्रलिपी स्वरूपाची आहे आणि अजूनही न वाचलेली आहे, नंतरच्या ब्राह्मी, देवनागरी किंवा खरोष्ठी लिपींप्रमाणे नाही.", en: "Harappan script is pictographic in nature and remains undeciphered, unlike later Brahmi, Devanagari, or Kharosthi scripts." } },
    { id: 41, question: { mr: "चुंबकाच्या कोणत्या गुणधर्मामुळे ते लोहाला आकर्षित करते?", en: "Due to which property of magnet does it attract iron?" }, options: { mr: ["गुरुत्वाकर्षण", "चुंबकीय क्षेत्र", "विद्युत प्रवाह", "तापीय ऊर्जा"], en: ["Gravity", "Magnetic field", "Electric current", "Thermal energy"] }, correct: 1, explanation: { mr: "चुंबक त्यांच्या चुंबकीय क्षेत्रामुळे लोहाला आकर्षित करतात, गुरुत्वाकर्षण, विद्युत प्रवाह किंवा तापीय ऊर्जेमुळे नाही.", en: "Magnets attract iron due to their magnetic field, not gravity, electric current, or thermal energy." } },
    { id: 42, question: { mr: "चुंबकाचे दोन ध्रुव कोणते आहेत?", en: "What are the two poles of a magnet?" }, options: { mr: ["पूर्व आणि पश्चिम", "उत्तर आणि दक्षिण", "सकारात्मक आणि नकारात्मक", "उच्च आणि निम्न"], en: ["East and West", "North and South", "Positive and Negative", "High and Low"] }, correct: 1, explanation: { mr: "प्रत्येक चुंबकाचे दोन ध्रुव असतात: उत्तर आणि दक्षिण, सकारात्मक-नकारात्मक (विद्युत) किंवा पूर्व-पश्चिम दिशांप्रमाणे नाही.", en: "Every magnet has two poles: North and South, unlike positive-negative (electric) or east-west directions." } },
    { id: 43, question: { mr: "चुंबकाला उष्णता दिल्यास त्याचे चुंबकीय गुणधर्म कसे बदलतात?", en: "How do the magnetic properties of a magnet change when heated?" }, options: { mr: ["वाढतात", "कमी होतात किंवा नष्ट होतात", "स्थिर राहतात", "दुप्पट होतात"], en: ["Increase", "Decrease or get destroyed", "Remain stable", "Double"] }, correct: 1, explanation: { mr: "चुंबकाला त्याच्या क्यूरी तापमानापेक्षा जास्त गरम केल्यास आण्विक संरचना बिघडल्यामुळे त्याचे चुंबकीय गुणधर्म कमी होतात किंवा नष्ट होतात.", en: "Heating a magnet beyond its Curie temperature reduces or destroys its magnetic properties due to molecular structure disruption." } },
    { id: 44, question: { mr: "उष्णतेचे वहन (Conduction) कोणत्या माध्यमात सर्वात प्रभावीपणे होते?", en: "In which medium does heat conduction occur most effectively?" }, options: { mr: ["द्रव", "घन", "वायू", "निर्वात"], en: ["Liquid", "Solid", "Gas", "Vacuum"] }, correct: 1, explanation: { mr: "उष्णता वहन घन पदार्थांमध्ये (विशेषतः धातूंमध्ये) सर्वात प्रभावी होते कारण रेणू जवळजवळ पॅक केलेले असतात, द्रव, वायू किंवा निर्वातच्या तुलनेत.", en: "Heat conduction is most efficient in solids (especially metals) due to closely packed molecules, compared to liquids, gases, or vacuum." } },
    { id: 45, question: { mr: "उष्णतेचे मापन कोणत्या एककात केले जाते?", en: "In which unit is heat measured?" }, options: { mr: ["न्यूटन", "जूल", "वॅट", "केल्विन"], en: ["Newton", "Joule", "Watt", "Kelvin"] }, correct: 1, explanation: { mr: "उष्णता, ऊर्जेचा एक प्रकार असल्याने, जूलमध्ये मोजली जाते, तर केल्विन तापमान मोजते, वॅट शक्ती मोजते आणि न्यूटन बल मोजते.", en: "Heat, being a form of energy, is measured in Joules, while Kelvin measures temperature, Watt measures power, and Newton measures force." } },
    { id: 46, question: { mr: "उष्णतेच्या संवहन (Convection) प्रक्रियेत कोणत्या प्रकारची हालचाल होते?", en: "What type of movement occurs in the convection process of heat?" }, options: { mr: ["रेणूंची कंपने", "द्रव किंवा वायूची वहन हालचाल", "किरणोत्सर्ग", "विद्युत प्रवाह"], en: ["Molecular vibrations", "Bulk movement of liquid or gas", "Radiation", "Electric current"] }, correct: 1, explanation: { mr: "संवहनामध्ये द्रव किंवा वायूंची मोठ्या प्रमाणात हालचाल होते जिथे गरम पदार्थ वर येतो आणि थंड पदार्थ खाली जातो.", en: "Convection involves bulk movement of liquids or gases where hot material rises and cold material sinks." } },
    { id: 47, question: { mr: "पाण्याचे उष्णतेचे अव्यक्त उष्णता (Latent Heat) कोणत्या प्रक्रियेत महत्त्वाची आहे?", en: "In which process is the latent heat of water important?" }, options: { mr: ["हवेचे तापमान वाढवणे", "पाण्याचे उकळणे किंवा गोठणे", "धातू वितळणे", "विद्युत निर्मिती"], en: ["Increasing air temperature", "Boiling or freezing of water", "Melting metals", "Electricity generation"] }, correct: 1, explanation: { mr: "अव्यक्त उष्णता ही तापमान बदल न करता अवस्था बदलासाठी (उकळणे/गोठणे) आवश्यक ऊर्जा आहे.", en: "Latent heat is the energy required for phase transitions (boiling/freezing) without temperature change." } },
    { id: 48, question: { mr: "मानवी हृदयात किती कप्पे (Chambers) असतात?", en: "How many chambers are there in the human heart?" }, options: { mr: ["दोन", "तीन", "चार", "पाच"], en: ["Two", "Three", "Four", "Five"] }, correct: 2, explanation: { mr: "मानवी हृदयात चार कप्पे आहेत: दोन अट्रिया (वरचे कप्पे) आणि दोन वेंट्रिकल (खालचे कप्पे).", en: "Human heart has four chambers: two atria (upper chambers) and two ventricles (lower chambers)." } },
    { id: 49, question: { mr: "हृदयातून रक्त शरीरात पाठवणारी रक्तवाहिनी कोणती आहे?", en: "Which blood vessel carries blood from the heart to the body?" }, options: { mr: ["शिरा (Vein)", "महाधमनी (Aorta)", "केशिका (Capillary)", "फुप्फुस शिरा"], en: ["Vein", "Aorta", "Capillary", "Pulmonary vein"] }, correct: 1, explanation: { mr: "महाधमनी ही मुख्य धमनी आहे जी हृदयातून शरीरात ऑक्सिजनयुक्त रक्त पोहोचवते, तर शिरा हृदयाकडे रक्त आणतात.", en: "Aorta is the main artery that carries oxygenated blood from the heart to the body, while veins carry blood to the heart." } },
    { id: 50, question: { mr: "हृदयाच्या कशामुळे धडधड (Heartbeat) निर्माण होते?", en: "What causes the heartbeat in the heart?" }, options: { mr: ["सायनो-अॅट्रियल नोड (SA Node)", "रक्तदाब", "फुप्फुस", "यकृत"], en: ["Sino-Atrial Node (SA Node)", "Blood pressure", "Lungs", "Liver"] }, correct: 0, explanation: { mr: "SA Node हृदयाचा नैसर्गिक पेसमेकर आहे, जो विद्युत संकेत निर्माण करून हृदयाची गती नियंत्रित करतो.", en: "SA Node acts as the heart's natural pacemaker, generating electrical impulses that regulate heartbeat rhythm." } }
  ]
};

export const getPromotionalTest = (language = 'mr') => {
  return {
    ...promotionalTestData,
    title: promotionalTestData.title[language],
    description: promotionalTestData.description[language],
    questions: promotionalTestData.questions.map(q => ({
      ...q,
      question: q.question[language],
      options: q.options[language],
      explanation: q.explanation ? q.explanation[language] : undefined
    }))
  }
};